# Generated by Django 4.0.4 on 2022-06-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(max_length=300, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('product_name', models.CharField(max_length=300)),
                ('categName', models.CharField(max_length=300)),
                ('product_qty', models.IntegerField()),
            ],
        ),
    ]
