# Generated by Django 4.0.4 on 2022-06-22 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='product_id',
            new_name='product',
        ),
    ]
