# Generated by Django 4.0.4 on 2022-06-14 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_products'),
        ('cart', '0002_cart_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='categName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.categ'),
        ),
    ]
